# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: stixez.SyncCrate
PackageVersion: 0.7.5
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stixez/SyncCrate/releases/download/v0.7.5/SyncCrate_0.7.5_x64-setup.exe
  InstallerSha256: A4F7F3E24D9DBD8B64675B64B94D5D5626A247AD379E43B7E0545635C54126C3
ManifestType: installer
ManifestVersion: 1.12.0
